apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: test-container
      image: nginx:1.6                                                              
      ports:
      - containerPort: 80  
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
        items:
        - key: SPECIAL_LEVEL
          path: keys
  restartPolicy: Never