
bosun-simple-app:
  bosun:
    name: "demo"
    team: "agrippa"
    gitrepo: "demo"
    fullnameOverride: ""
    buildFQDN: true
    forcePodRollWhenHelm: true

  container:
    repository: "549050352176.dkr.ecr.us-east-1.amazonaws.com/demo-springboot-agrippa"
    tag: "1.0.0"
    replicaCount: 1
    port: 8090
    # env:
      # - name:
      #   value:
    pullPolicy: Always
    pullSecrets: []
    podAnnotations:
      # iam.amazonaws.com/role: arn:aws:iam::<AWS Account Id>:role/pods_will_use_for_AWS_access
      # prometheus.io/path: /prometheus-metrics
      # prometheus.io/port: "8081"
      prometheus.io/scrape: "false"      
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: config-volume
      mountPath: /etc/config
    volumes:
      - name: tmp
        emptyDir: {}
      - name: config-volume
        configMap:
          name: example
    livenessDelay: 10
    livenessProbe:
      httpGet:
        port: 8090
        path: /actuator/health
      initialDelaySeconds: 10
    readinessProbe:
      httpGet:
        port: 8090
        path: /actuator/health
    healthCheck: /actuator/health
    healthCheckPort: 8090

  serviceAccount:
    create: true
    privileged: false
    writablefs: true
    name: "demo"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    class: private
    tlsIssuer: letsencrypt-environment-subdomain
    host: "demo"
    path: /
    annotations: {}

  resources:
    limits:
      cpu: 600m
      memory: 256Mi
    requests:
      cpu: 300m
      memory: 128Mi

  podSecurityContext: {}
    # runAsUser: 1001
    # runAsGroup: 1001
    # fsGroup: 1001

  nodeSelector: {}

  tolerations: []

  affinity: {}
